package com.famatodo.error;

public enum ClientError {

	CLIENT_WITH_IDENTIFICATION_NUMBER_ALREADY_EXIST, CLIENT_DOESNT_EXIST,
	EMAIL_OR_USERNAME_ARE_ALREADY_REGISTERED_FOR_OTHER_CLIENT, CLIENT_IS_DISABLED,
	IDENTIFICATION_NUMBER_IS_REQUIRED,USERNAME_DOESNT_EXIST, PASSWORD_INCORRECT
}
